#' Boat effort per study week
#'
#' [boat_effort_per_week()] generates a [tibble][tibble::tibble-package]
#' encoding the boat effort aggregated per study week, i.e. how much time spent
#' on a specific grid cell or detector, per study week.
#'
#' @param boat_trips A [tibble][tibble::tibble-package] of track data (boat
#'   trips). Data should be aggregated on a specific time interval, e.g.
#'   minutes.
#' @param grid A [RasterLayer][raster::raster] object.
#' @param coordinates The type of coordinates in the output: `"utm"` (default)
#'   or `"longlat"`.
#'
#' @return A [tibble][tibble::tibble-package] of three plus n columns, where n
#'   is the number of occasions. The first three columns are: `index`, the
#'   detector identifier or index; `easting` and `northing`, or `longitude` and
#'   `latitude`.
#'
#' @examples
#' boat_effort_per_week()
#'
#' @importFrom rlang .data
#' @export
boat_effort_per_week <-
  function(boat_trips = azores.fkw::boat_trips_by_min,
           grid = create_grid(),
           coordinates = c("utm", "longlat")) {

  if (!rlang::has_name(boat_trips, "trip"))
    stop("`boat_trips` must have a column named trip")

    if (!rlang::has_name(boat_trips, "week"))
      stop("`boat_trips` must have a column named week")

  if (!rlang::has_name(boat_trips, "longitude"))
    stop("`boat_trips` must have a column named longitude")

  if (!rlang::has_name(boat_trips, "latitude"))
    stop("`boat_trips` must have a column named latitude")

  coordinates <- match.arg(coordinates)

  # Find detectors for any given moment of `boat_trips`
  detectors <- find_grid_cells(points = boat_trips, grid = grid)

  effort <-
    boat_trips["week"] |>
    dplyr::bind_cols(detectors) |>
    dplyr::count(.data$week,
                 .data$index,
                 .data$longitude,
                 .data$latitude,
                 name = "total_minutes") |>
    tidyr::pivot_wider(
      names_from = c("week"),
      values_from = "total_minutes",
      values_fill = 0L
    )

  # Change effort to use UTM instead of Longitude/Latitude coordinates
  if (identical(coordinates, "utm")) {
    longlat <-
      dplyr::rename(effort[c("latitude", "longitude")],
                    lat = .data$latitude,
                    lon = .data$longitude)

    utm <- longlat_to_utm(longlat)
    effort <- tibble::tibble(effort["index"], utm[c("easting", "northing")], effort[-(1:3)])
  }

  effort
}

#' Boat effort per average week
#'
#' [boat_effort_per_avg_week()] calculates the boat effort per week on average.
#' This function takes the results per week as generated by
#' [boat_effort_per_week()] and calculates the mean per grid cell / detector.
#'
#' @param boat_effort_per_week A tibble as output by [boat_effort_per_week()].
#'
#' @returns A tibble of four columns: `index` (index of the grid cell /
#'   detector), UTM coordinates (`easting` and `northing`), and the average boat
#'   effort per week per grid point (`boat_effort`).
#'
#' @examples
#' boat_effort_per_avg_week()
#'
#' @export
boat_effort_per_avg_week <- function(boat_effort_per_week = azores.fkw::boat_effort_per_week()) {
  boat_effort_per_week |>
    dplyr::rowwise() |>
    dplyr::mutate(boat_effort = mean(dplyr::c_across(dplyr::matches("week")), na.rm = TRUE)) |>
    dplyr::select(c("index", "easting", "northing", "boat_effort")) |>
    dplyr::ungroup()
}

#' Total boat effort per grid point
#'
#' [boat_effort_for_all_weeks()] calculates the total boat effort per grid
#' point. This function takes the results per week as generated by
#' [boat_effort_per_week()] and calculates the sum of all boat efforts across
#' all weeks per grid cell / detector.
#'
#' @param boat_effort_per_week A tibble as output by [boat_effort_per_week()].
#'
#' @returns A tibble of four columns: `index` (index of the grid cell /
#'   detector), UTM coordinates (`easting` and `northing`), and the total (sum)
#'   boat effort per week per grid point (`boat_effort`).
#'
#' @examples
#' boat_effort_for_all_weeks()
#'
#' @export
boat_effort_for_all_weeks <- function(boat_effort_per_week = azores.fkw::boat_effort_per_week()) {
  boat_effort_per_week |>
    dplyr::rowwise() |>
    dplyr::mutate(boat_effort = sum(dplyr::c_across(dplyr::matches("week")), na.rm = TRUE)) |>
    dplyr::select(c("index", "easting", "northing", "boat_effort")) |>
    dplyr::ungroup()
}

total_boat_effort_per_week <- function(boat_effort_per_week = azores.fkw::boat_effort_per_week()) {

  colSums(boat_effort_per_week[grepl(pattern = "week", colnames(boat_effort_per_week))]) |>
    as.list() |>
    tibble::as_tibble()
}

#' Lookout effort per week
#'
#' [lookout_effort_by_week()] takes lookout scores and boat efforts per week
#' in minutes, and calculates the lookout effort per week. Essentially, the
#' lookout score is always the same but it is re-scaled here according to the
#' time the boat spent on each position. The boat trip duration is used as
#' a proxy for the lookout watching time.
#'
#' @param lookout_score_tbl A tibble with lookout scores. See [lookout_score()].
#' @param boat_effort_per_week_tbl A tibble with boat effort per week, in
#'   minutes, see [boat_effort_per_week()].
#'
#' @returns A tibble where boat effort in minutes has been converted to lookout
#' effort, also in minutes.
#'
#' @importFrom rlang .data
#' @export
lookout_effort_by_week <- function(lookout_score_tbl = lookout_score(),
                                   boat_effort_per_week_tbl = boat_effort_per_week()) {

  total_boat_effort <- total_boat_effort_per_week(boat_effort_per_week = boat_effort_per_week_tbl)

  joined_tbl <- dplyr::bind_cols(lookout_score_tbl, total_boat_effort)

  dplyr::mutate(joined_tbl,
                dplyr::across(
                  dplyr::matches("week"),
                  ~ .x * .data$lookout_score_normalized
                )) |>
    dplyr::select(-c("lookout_score", "lookout_score_normalized")) |>
    dplyr::relocate(.data$longitude, .data$latitude, .after = "northing")

}

#' Lookout effort for all weeks
#'
#' [lookout_effort_for_all_weeks()] calculates the lookout effort per trip on
#' average. This function takes the results generated by [lookout_score()] and
#' calculates the total lookout effort for the number of trips given in
#' `ntrips`.
#'
#' @param lookout_effort_by_week A tibble as output by [lookout_effort_by_week()].
#'
#' @returns A tibble with the same structure as the value returned by
#'   [lookout_score()] with an extra column: `lookout_effort`, i.e. the total
#'   lookout effort corresponding to the all weeks.
#'
#' @examples
#' lookout_effort_for_all_weeks()
#'
#' @export
lookout_effort_for_all_weeks <- function(lookout_effort_by_week = azores.fkw::lookout_effort_by_week()) {
  total_lookout_effort_by_detector <- rowSums(lookout_effort_by_week[grepl(pattern = "week", colnames(lookout_effort_by_week))])
  cols <- c("index", "easting", "northing", "longitude", "latitude")

  dplyr::bind_cols(lookout_effort_by_week[cols], lookout_effort = total_lookout_effort_by_detector)

}

#' Lookout effort per average week
#'
#' [lookout_effort_per_avg_week()] calculates the lookout effort per week on average.
#' This function takes the results generated by
#' [lookout_score()] and calculates average lookout effort by simply multiplying
#' the effort score by the boat weekly average duration.
#'
#' @param lookout_effort_by_week A tibble as output by [lookout_effort_by_week()].
#'
#' @returns A tibble with the same structure as the value returned by
#'   [lookout_score()] with an extra column: `lookout_effort`, i.e. the lookout
#'   effort per average weekly boat trip duration, in minutes.
#'
#' @examples
#' lookout_effort_per_avg_week()
#'
#' @export
lookout_effort_per_avg_week <- function(lookout_effort_by_week = azores.fkw::lookout_effort_by_week()) {
  lookout_effort_for_all_weeks <- lookout_effort_for_all_weeks(lookout_effort_by_week = lookout_effort_by_week)
  n_weeks <- sum(grepl(pattern = "week", colnames(lookout_effort_by_week)))

  lookout_effort_for_all_weeks |>
    dplyr::mutate(lookout_effort = .data$lookout_effort / n_weeks)
}

#' Combined effort
#'
#' [combined_effort_for_all_weeks()] determines the combined effort, i.e. the total of boat
#' and lookout efforts for all the study duration period.
#'
#' @param boat_effort A tibble as returned by [boat_effort_for_all_weeks()].
#' @param lookout_effort A tibble as returned by [lookout_effort_for_all_weeks()].
#'
#' @returns A tibble with one row per spatial position, with the following
#'   columns:
#'
#' - `index`: An index for each grid position / detector.
#' - `easting`: Easting coordinate.
#' - `northing`: Northing coordinate.
#' - `longitude`: Longitude, in decimal degrees.
#' - `latitude`: Latitude, in decimal degrees.
#' - `lookout_score`: Lookout score, as calculated with [logistic_2d()].
#' - `lookout_score_normalized`: Normalized lookout score, the same as
#'   `lookout_score` but normalized for the total over the score over the whole
#'   study area.
#' - `lookout_effort`: Total lookout effort, in minutes, for the whole study
#'    duration time.
#' - `boat_effort`: Total boat effort, in minutes, for the whole study
#'    duration time.
#' - `combined_effort`: The sum of `lookout_effort` and `boat_effort`, in
#'   minutes, for the whole study duration time.
#'
#' @examples
#'
#' combined_effort_for_all_weeks()
#'
#' @export
combined_effort_for_all_weeks <- function(boat_effort = boat_effort_for_all_weeks(),
                            lookout_effort = lookout_effort_for_all_weeks()) {
  dplyr::left_join(lookout_effort,
                   boat_effort,
                   by = c("index", "easting", "northing"), ) |>
    dplyr::mutate(boat_effort = dplyr::if_else(is.na(.data$boat_effort), 0L, .data$boat_effort)) |>
    dplyr::mutate(combined_effort = .data$boat_effort + .data$lookout_effort)
}


#' [combined_effort_per_week()] determines the combined effort, i.e. the total of boat
#' and lookout efforts for every week.
#'
#' @param boat_effort_per_week A tibble of boat effort per individual week. See [boat_effort_per_week()].
#' @param lookout_effort_by_week A tibble of lookout effort per individual week. See [lookout_effort_by_week].
#'
#' @returns A [tibble][tibble::tibble-package] of five plus n columns, where n
#'   is the number of occasions (weeks). The first five columns are: `index`, the
#'   detector identifier or index; `easting` and `northing`, or `longitude` and
#'   `latitude`.
#'
#' @importFrom rlang .data
#' @export
combined_effort_per_week <- function(boat_effort_per_week = azores.fkw::boat_effort_per_week(),
                                     lookout_effort_by_week = azores.fkw::lookout_effort_by_week()) {
  # `boat_effort_per_week2`: Boat effort including detectors surveyed for the
  # lookout effort whose values for boat effort are zero.
  boat_effort_per_week2 <-
    boat_effort_per_week |>
    dplyr::right_join(lookout_effort_by_week[c("index", "easting", "northing")],
                      by = c("index", "easting", "northing")) |>
    dplyr::mutate(dplyr::across(dplyr::matches("week"), ~ tidyr::replace_na(.x, replace = 0)))

  lookout_effort_by_week_long <- tidyr::pivot_longer(
    lookout_effort_by_week,
    cols = dplyr::starts_with("week"),
    names_to = "week",
    values_to = "lookout_effort"
  )
  boat_effort_by_week_long <- tidyr::pivot_longer(
    boat_effort_per_week2,
    cols = dplyr::starts_with("week"),
    names_to = "week",
    values_to = "boat_effort"
  )

  combined_effort_by_week_long <-
    dplyr::inner_join(
      x = lookout_effort_by_week_long,
      y = boat_effort_by_week_long,
      by = c("index", "easting", "northing", "week")
    ) |>
    dplyr::mutate(combined_effort = .data$lookout_effort + .data$boat_effort)

  combined_effort_by_week_wide <-
    combined_effort_by_week_long |>
    dplyr::select(-c("lookout_effort", "boat_effort")) |>
    tidyr::pivot_wider(names_from = "week", values_from = "combined_effort")

  combined_effort_by_week_wide
}
