#' Get occasions from effort
#'
#' [occasions()] generates a [tibble][tibble::tibble-package] of occasions from
#' the columns in an effort tibble.
#'
#' @param effort An object as generated by [effort()].
#'
#'
#' @return A [tibble][tibble::tibble-package] of four columns:
#' \describe{
#' \item{`occasion_id`}{An identifier for each occasion.}
#' \item{`trip`}{A character vector of trips.}
#' \item{`date`}{The date of the occasion.}
#' \item{`time`}{The time of the occasion.}
#' }
#'
#' @importFrom rlang .data
#' @export
# occasions <- function(effort = azores.fkw::effort()) {
#
#   # All columns except `index`, `easting`/`longitude` and `northing`/`latitude`.
#   trips <- colnames(effort)[-(1:3)]
#
#   tibble::tibble(trip = trips) |>
#     tibble::rowid_to_column("occasion_id") |>
#     dplyr::mutate(date = lubridate::as_date(.data$trip),
#                   time = hms::as_hms(lubridate::ymd_hms(.data$trip)))
#
# }
